theme: minima
title: Notas de Programación
author: Priscilla Clark
description: > # this means to ignore newlines until "baseurl:"
  Gracias por visitar

# social links
twitter_username: prisandia # DO NOT include the @ character, or else the build will fail!
github_username:  priscillaclark # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
