theme: minima
title: Notas
author: Priscilla Clark
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Notas de Programacion

# social links
twitter_username: prisandia # DO NOT include the @ character, or else the build will fail!
github_username:  priscillaclark # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
